In [2]:
import numpy as np 
import os 

array = np.array([[2,4,5,6], [6,7,8,9]])
filter = array < 5
print('filter sampple', filter)

filter sampple [[ True  True False False]
 [False False False False]]


In [34]:
import numpy as np
import os

destino = "../olis_sells/data/raw"
file_name = "olist_order_payments_dataset.csv"
# complete_file_name = os.path.join(destino, "ollis_order_payments_dataset.csv")
# print("borrame", complete_file_name)

np_original_array = np.genfromtxt(os.path.join(destino, file_name), delimiter=",", skip_header=1)
print('np original array: \n', np_original_array)
original_shape = np_original_array.shape
print('np_original_array shape: \n', original_shape)

np original array: 
 [[   nan   1.      nan   8.    99.33]
 [   nan   1.      nan   1.    24.39]
 [   nan   1.      nan   1.    65.71]
 ...
 [   nan   1.      nan   1.    47.77]
 [   nan   1.      nan   5.   369.54]
 [   nan   1.      nan   1.   191.58]]
np_original_array shape: 
 (103886, 5)


### Lets add a ones vector lettings "nan values" intact

In [4]:
changed_original = np_original_array + np.ones(original_shape)*1
print('changed original array: \n', changed_original)

changed original array: 
 [[   nan    nan    nan    nan    nan]
 [   nan   2.      nan   9.   100.33]
 [   nan   2.      nan   2.    25.39]
 ...
 [   nan   2.      nan   2.    48.77]
 [   nan   2.      nan   6.   370.54]
 [   nan   2.      nan   2.   192.58]]


### Lets add 2 vector full of 2's inside our original_array cleaned version 

In [39]:

# Limpiar el arreglo para eliminar los nan
cleaned_arr = np.isfinite(np_original_array)
cleaned_arr_shape = cleaned_arr.shape
print('original_shape: \n', original_shape, ' \n cleaned_arr_shape: \n', cleaned_arr_shape)

filtered_array = ~np.isnan(np_original_array)
# Filtrar el arreglo original con np.where (el 0 susttuye los varoles)
filtered_array = np.where(np.isnan(np_original_array), 0, np.ones(original_shape))
# print('filtered_array', filtered_array)

added_array = np.add(np_original_array, filtered_array*10)
print('added array', filtered_array)

original_shape: 
 (103886, 5)  
 cleaned_arr_shape: 
 (103886, 5)
added array [[0. 1. 0. 1. 1.]
 [0. 1. 0. 1. 1.]
 [0. 1. 0. 1. 1.]
 ...
 [0. 1. 0. 1. 1.]
 [0. 1. 0. 1. 1.]
 [0. 1. 0. 1. 1.]]


### Crear una matriz aleatoria del tamaño del original array

In [21]:
random_array = np.random.rand(np_original_array.flatten().size)
print('Vector random del tamaño del vector original: \n', random_array)

Vector random del tamaño del vector original: 
 [0.7268871  0.16221102 0.38830221 ... 0.51076506 0.86497226 0.65699478]


### Funciones con abrstracciń matemática probaré algunas

In [33]:
#La primera es para potencias(y raices)
np.power(random_array, 1/2)

#Ahora obtendremos el redondeo a su entero más cercano
np.round(1 + random_array)

array([2., 1., 1., ..., 2., 2., 2.], shape=(519435,))

### Ahora quiero probar algo con linspace y arange

In [25]:
linspace_prueba = np.linspace(0,1,3)
linspace_mean = np.mean(linspace_prueba)
print('linspace mean', linspace_mean)
arange_prueba = np.arange(0,10,0.5)
print('arange type:', arange_prueba.dtype)

linspace mean 0.5
arange type: float64
